### ISSUE TITLE
reason: Missing output files: mean_and_std_of_dataset.txt

### ISSUE THREAD

**Issue by AlaaBessadok** [JacobHanimann/scDINO#3]
Hello, super interesting work! I would like to train it on my cell dataset but I am not familiar with snakemake. I tried to pretain the model using the command shared in the README.md and I got this error, could you please share some recommendation to solve this and be able to get mean and std of my dataset? Thanks in advance! <img width="1023" alt="Screenshot 2023-07-17 at 15 20 22" src="https://github.com/JacobHanimann/scDINO/assets/67750721/ef9d5bc4-0a7e-4a99-b64d-2fd9d324d1b0">

**Comment by JacobHanimann** [comment]
Please have a look at https://github.com/JacobHanimann/scDINO/issues/2 :)
