### ISSUE TITLE
CLS features all nan when passing in 4 channel images.

### ISSUE THREAD

**Issue by MikeLippincott** [JacobHanimann/scDINO#5]
I am using scDINO on my image sets. I have four channel fluorescence images. To make my images compatible with the pre-trained model, I made a 5th channel with all 0's.

This is an example of how I make my blank channel(s).
Where image is the loaded image via the `tifffile` python package
```python
if image.shape[-1] < 5:
        channels_to_add = 5 - image.shape[-1]
        for channel in range(channels_to_add):
            # add a new channel of all zeros
            new_channels = np.zeros((image.shape[0], image.shape[1], 1))
            image_merge = np.concatenate((image,new_channels), axis=-1)
    print(image_merge.shape)
```

The issue I am having in scDINO seems to arise in the `normalize_numpy_0_to_1` & `normalize_tensor_per_channel` functions in the [pyscripts/utils.py](https://github.com/JacobHanimann/scDINO/blob/c33646c0b9b77bec5712b8da5f5c76ff395682c6/pyscripts/utils.py) file. 
When I have a channel of a uniform distribution of pixel values I end up with a normalized array value in the uniformly distributed channel of NaN due to the zerodivision that occurs on `lines 78 & 108`.     

I have a proposed change that would help scDINO use multichannel images that contain uniform distributions. 
If the maintainers of scDINO agree with the proposed change I can happily open a PR from this issue! 
The proposed change is below.

```python
def normalize_numpy_0_to_1(x):
    print("x",x.shape)
    x_min = x.min(axis=(0,1), keepdims=True)
    x_max = x.max(axis=(0,1), keepdims=True)
    diff_min_max = x_max - x_min
    if check_nan(diff_min_max):
        print("diff_min_max is nan")
    if check_nan(x-x_min):
        print("x-x_min is nan:")
    if check_nan(x):
        print("x contains nan before normalization")
    if check_zero(diff_min_max):
        print("diff_min_max has zero")
        print("x_max",x_max)
        print("x_min",x_min)
        print("diff_min_max",diff_min_max)
        print("x",x.shape)
        # replace x_max 0 values with 1
        for i in range(len(x_max[0][0])):
            if x_max[0][0][i] == 0:
                x_max[0][0][i] = 1
    x = (x - x_min)/(x_max-x_min)
    if check_nan(x):
        print("x contains nan after normalization")
    return x
```

Excellent work on scDINO and implementations! I would love to talk more in the future!

**Comment by JacobHanimann** [comment]
Hi Mike, your solution sounds great to me. I accepted your PR. Thanks for your interest in scDINO and your contribution!😃
